package com.bytedance.android.input.popup;

/* loaded from: classes.dex */
public enum WindowId {
    CONFIRM_SPEECH_PERMISSION,
    CONFIRM_RECOMMEND_PERMISSION,
    CONFIRM_ACCESSIBILITY_PERMISSION,
    CONFIRM_LOGIN,
    TOAST_OF_IME_WARNING,
    PREVIEW_IMAGES,
    OPEN_FULL_INPUT_MODE,
    APP_UPGRADE_TIPS_UI,
    FUSIYIN_SWIPE_UP_TIPS_UI,
    CAPS_LOCK_TIPS_UI,
    SWIPE_DOWN_WITHDRAW_TIPS_UI,
    ASR_PUNCT_SETTINGS_TIPS_UI,
    SMS_READ_VERIFICATION_PERMISSION_TIPS,
    ASR_SWITCH_CELL_SETTINGS_TIPS_UI,
    CONFIRM_SMS_READ_PERMISSION,
    CONFIRM_READ_CONTACTS_PERMISSION,
    CONFIRM_DOWNLOAD_MODEL_TIPS_UI,
    CLIPBOARD_HISTORY,
    CLEAR_CONTACTS_HISTORY,
    LEXICON_MANAGEMENT,
    ENTER_KEY_SEND_MSG_CONFIRM,
    ASSOCIATE_CLOSE,
    CUSTOM_TOOLBAR_UI,
    OFFLINE_MODEL_DELETE_TIPS
}
