package com.mammon.audiosdk.enums;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.ss.android.socialbase.downloader.constants.DownloadConstants;
import com.ss.android.socialbase.downloader.constants.DownloadErrorCode;
import java.util.HashMap;

/* loaded from: classes2.dex */
public enum SAMICorePropertyId {
    SAMICorePropertyID_Base_NAME(0),
    SAMICorePropertyID_Base_UNKNOWN(1),
    SAMICorePropertyID_Processor_ContextPrepare(100),
    SAMICorePropertyID_VAD_Aggressiveness_Mode_Name(200),
    SAMICorePropertyID_VAD_Silence_Robust_Length_name(201),
    SAMICorePropertyID_VAD_Frame_Time_Length_Name(202),
    SAMICorePropertyID_VAD_Smoothing_Searching_Width_Name(203),
    SAMICorePropertyID_VAD_Smoothing_Searching_Threshold_Ratio_Name(204),
    SAMICorePropertyID_VAD_Overall_Moving_Average_Width_Name(205),
    SAMICorePropertyID_VAD_Overall_Searching_Threshold_Ratio_Name(206),
    SAMICorePropertyID_VAD_Overall_Silence_Length_Name(207),
    SAMICorePropertyID_Compressor_Bypass(300),
    SAMICorePropertyID_Compressor_Ratio(301),
    SAMICorePropertyID_Compressor_Threshold(302),
    SAMICorePropertyID_Compressor_Knee_dB(303),
    SAMICorePropertyID_Compressor_Attack(304),
    SAMICorePropertyID_Compressor_Release(305),
    SAMICorePropertyID_Compressor_Auto_Makeup_Gain(306),
    SAMICorePropertyID_Compressor_Output_Gain_dB(307),
    SAMICorePropertyID_Compressor_Look_Head(308),
    SAMICorePropertyID_FrameFeatures(400),
    SAMICorePropertyID_FrameFeature_SPECTRUM(TypedValues.CycleType.TYPE_CURVE_FIT),
    SAMICorePropertyID_FrameFeature_ONSET(TypedValues.CycleType.TYPE_VISIBILITY),
    SAMICorePropertyID_FrameFeature_F0(TypedValues.CycleType.TYPE_ALPHA),
    SAMICorePropertyID_FrameFeature_BEAT_TRACKING(404),
    SAMICorePropertyID_FrameFeature_VOLUME(405),
    SAMICorePropertyID_FrameFeature_NNVAD(406),
    SAMICorePropertyID_FrameFeature_Voice_Activity(407),
    SAMICorePropertyID_FrameFeature_KWS(408),
    SAMICorePropertyID_FrameFeature_AudioMetrics(409),
    SAMICorePropertyID_FrameFeature_SHORTTERM_LOUDNESS(410),
    SAMICorePropertyID_FrameFeature_MOMENTARY_LOUDNESS(411),
    SAMICorePropertyID_FrameFeature_AudioMetricsV2(DownloadConstants.HTTP_PRECON_FAILED),
    SAMICorePropertyID_FrameFeature_SNR(413),
    SAMICorePropertyID_FrameFeature_Aed_STATISTIC(414),
    SAMICorePropertyID_FrameFeature_VOICE_ACTIVITY_DETECTION_STATISTIC(415),
    SAMICorePropertyID_FrameFeature_MULTILEVEL_WAKEUP(416),
    SAMICorePropertyID_OverallFeatures(500),
    SAMICorePropertyID_OverallFeature_GLOBAL_LOUDNESS(TypedValues.PositionType.TYPE_TRANSITION_EASING),
    SAMICorePropertyID_OverallFeature_GLOBAL_PEAK(TypedValues.PositionType.TYPE_DRAWPATH),
    SAMICorePropertyID_OverallFeature_TRACKING_OFFLINE_OVERALL(TypedValues.PositionType.TYPE_PERCENT_WIDTH),
    SAMICorePropertyID_OverallFeature_NNVAD_OVERALL(TypedValues.PositionType.TYPE_PERCENT_HEIGHT),
    SAMICorePropertyID_OverallFeature_ONSET_OVERALL(TypedValues.PositionType.TYPE_SIZE_PERCENT),
    SAMICorePropertyID_OverallFeature_Voice_Activity_OVERALL(TypedValues.PositionType.TYPE_PERCENT_X),
    SAMICorePropertyID_SetExtractorFloatParameter(600),
    SAMICorePropertyID_SetExtractorStringParameter(601),
    SAMICorePropertyId_LoadModelBinary(TypedValues.TransitionType.TYPE_DURATION),
    SAMICorePropertyId_Seek(800),
    SAMICorePropertyId_TimeScaler(TypedValues.Custom.TYPE_INT),
    SAMICorePropertyId_TimeStretcher_TimeRatio(909),
    SAMICorePropertyId_TimeStretcher_PitchShift(910),
    SAMICorePropertyId_TimeStretcher_Reset(912),
    SAMICorePropertyId_TimeStretcher_GetSampleRate(914),
    SAMICorePropertyId_TimeStretcher_GetChannel(915),
    SAMICorePropertyId_TimeStretcher_UsePercussiveOption(916),
    SAMICorePropertyID_Processor_Prepare(1000),
    SAMICorePropertyID_Processor_SetParametersOffline(1001),
    SAMICorePropertyID_Processor_ContextUpdateFromFile(1002),
    SAMICorePropertyID_Processor_ContextUpdateFromString(1003),
    SAMICorePropertyID_Processor_ContextEmplaceParameterEventNow(1004),
    SAMICorePropertyID_Processor_ContextEmplaceParameterEventNowWithPlainValue(1005),
    SAMICorePropertyID_Processor_Loudnorm(1007),
    SAMICorePropertyID_Processor_Loudnorm2(1008),
    SAMICorePropertyID_AGC(DownloadErrorCode.ERROR_NO_SDCARD_PERMISSION),
    SAMICorePropertyID_AGC_SetTargetLevel(DownloadErrorCode.ERROR_RESPONSE_DATA_NOT_EQUALS),
    SAMICorePropertyID_AGC_SetGain(DownloadErrorCode.ERROR_GET_AVAILABLE_SPACE),
    SAMICorePropertyID_AGC_SetEnableLimiter(DownloadErrorCode.ERROR_TARGET_DIR_MKDIR_FAILED),
    SAMICoreEngineExecutorOutPut(1100),
    SAMICorePropertyID_KWS_KeyWords(1101),
    SAMICorePropertyID_KWS_Language(1102),
    SAMICorePropertyID_Common_Flush(1103),
    SAMICorePropertyID_Common_Reset(1104),
    SAMICorePropertyID_Common_SetParam(1105),
    SAMICorePropertyID_Common_SetInputEnd(1106),
    SAMICorePropertyID_Common_GetParam(1107),
    SAMICorePropertyID_Common_GetResult(1108),
    SAMICorePropertyID_Common_Wait_Stop(1109),
    SAMICorePropertyID_Common_CancelProcess(1110),
    SAMICorePropertyID_Common_AED_GetResult(1120),
    SAMICorePropertyID_MultiLevel_Wakeup_Command(1150),
    SAMICorePropertyID_MultiLevel_Wakeup_AudioBin(1151),
    SAMICorePropertyID_MultiLevel_Wakeup_Reset(1152),
    SAMICorePropertyID_MultiLevel_Wakeup_InputEnd(1153),
    SAMICorePropertyID_TCNDenoise(1200),
    SAMICorePropertyID_TCNDenoise_Rate(1201),
    SAMICorePropertyID_TCNDenoise_Mode(1202),
    SAMICorePropertyID_Processor_ContextChunkBinaryRes(1300),
    SAMICorePropertyID_Processor_ContextUpdateFromBinaryFile(1301),
    SAMICorePropertyID_Processor_ContextUpdateFromBinaryRes(1302),
    SAMICorePropertyID_Denoise_V2(1400),
    SAMICorePropertyID_Denoise_V2_Rate(1401),
    SAMICorePropertyID_Denoise_V2_Mode(1402),
    SAMICorePropertyID_SpeechRecognition(1500),
    SAMICorePropertyID_SpeechRecognition_Reset(1501),
    SAMICorePropertyID_SpeechRecognition_Finish(1502),
    SAMICorePropertyID_SpeechRecognition_UseWordInfo(1503),
    SAMICorePropertyID_SpeechRecognition_Resume(1504),
    SAMICorePropertyID_SpeechRecognition_UpdateRange(1505),
    SAMICorePropertyID_AudioMetrics_Rest_Executor(1511),
    SAMICorePropertyID_ASR_Offline(1520),
    SAMICorePropertyID_ASR_Offline_Set_Parameters(1521),
    SAMICorePropertyID_ASR_Offline_Rest_Executor(1522),
    SAMICorePropertyID_ASR_Offline_Finish(1523),
    SAMICorePropertyID_ASR_Offline_Finish_Result(1524),
    SAMICorePropertyId_ASR_Online_Reset_Recognition(1700),
    SAMICorePropertyID_Stream_TTS_Online_Force_Finish(1701),
    SAMICorePropertyID_Stream_TTS_Online_Wait_Stop(1702),
    SAMICorePropertyID_Stream_Play_TTS_Online_Force_Finish(1703),
    SAMICorePropertyId_ASR_Online_Force_Finish(1704),
    SAMICorePropertyId_ASR_Online_Start_Connect(1705),
    SAMICore_PropertyID_Stream_Play_TTS_Online_Set_TimeStrecher(1706),
    SAMICorePropertyId_ASR_Online_Wait_Stop(1709),
    SAMICorePropertyId_VC_Online(1710),
    SAMICorePropertyId_VC_Online_Open_Loudspeaker(1711),
    SAMICorePropertyId_VC_Online_Close_Loudspeaker(1712),
    SAMICorePropertyId_VC_Online_Audio_Start_Play(1713),
    SAMICorePropertyId_VC_Online_Audio_Stop_Play(1714),
    SAMICorePropertyId_VC_Online_Audio_Pause_Play(1715),
    SAMICorePropertyId_VC_Online_Audio_Resume_Play(1716),
    SAMICorePropertyId_VC_Online_Start_Server(1717),
    SAMICorePropertyId_VC_Online_Stop_Server(1718),
    SAMICorePropertyId_VC_Online_Stop_Server_Async(1719),
    SAMICorePropertyId_VC_Online_Force_Finish_Server(1720),
    SAMICorePropertyId_VC_Online_Set_Speaker(1721),
    SAMICorePropertyId_VC_Online_Get_Performance_Event_Tracking(1722),
    SAMICorePropertyId_VC_Online_Get_Input_Data_Save_File(1723),
    SAMICorePropertyId_VC_Online_Set_Input_Data_Uri(1724),
    SAMICorePropertyId_VC_Online_Set_Output_Data_Uri(1725),
    SAMICorePropertyId_VC_Online_Restart_Task(1726),
    SAMICorePropertyId_VC_Online_Cancel_Task(1727),
    SAMICorePropertyId_VC_Online_KeepAlive(1728),
    SAMICorePropertyId_Http_Common_Request_Force_Stop(1751),
    SAMICorePropertyID_Play_TTS_Performance(1760),
    SAMICorePropertyID_Stream_Play_TTS_Online_Playback_Gain(1761),
    SAMICorePropertyID_Bidirectional_TTS_Online_Force_Finish(1770),
    SAMICorePropertyID_Bidirectional_TTS_Online_Wait_Stop(1771),
    SAMICorePropertyID_Bidirectional_TTS_Online_Stop_Async(1772),
    SAMICorePropertyID_AudioMetricsJson(1800),
    SAMICorePropertyID_AudioMetrics_InputEnd(1801),
    SAMICorePropertyId_Voice_Assistant(2200),
    SAMICorePropertyId_Voice_Assistant_Set_Asr_Param(2201),
    SAMICorePropertyId_Voice_Assistant_Set_Tts_Param(2202),
    SAMICorePropertyId_Voice_Assistant_Start_Ws_Connect(2203),
    SAMICorePropertyId_Voice_Assistant_Stop_Ws_Connect(2204),
    SAMICorePropertyId_Voice_Assistant_Start_Task(2205),
    SAMICorePropertyId_Voice_Assistant_Finish_Task(2206),
    SAMICorePropertyId_Voice_Assistant_Start_Session(2207),
    SAMICorePropertyId_Voice_Assistant_Finish_Session(2208),
    SAMICorePropertyId_Voice_Assistant_Cancel_Session(2209),
    SAMICorePropertyId_Voice_Assistant_Cancel_Speech(2210),
    SAMICorePropertyId_Voice_Assistant_End_Asr(2211),
    SAMICorePropertyId_Voice_Assistant_Start_Tts(2212),
    SAMICorePropertyId_Voice_Assistant_Set_Aec_Param(2213),
    SAMICorePropertyId_Voice_Assistant_Interrupt_Call(2214),
    SAMICorePropertyId_Voice_Assistant_Pause_Call(2215),
    SAMICorePropertyId_Voice_Assistant_Continue_Call(2216),
    SAMICore_PropertyId_Voice_Assistant_Reconnect_Call(2217),
    SAMICore_PropertyId_Voice_Assistant_Mock_Stop_Ws_Connect(2218),
    SAMICorePropertyId_Voice_Assistant_Trigger_Bot(2219),
    SAMICorePropertyId_Voice_Assistant_Abort_Asr(2220),
    SAMICorePropertyId_Voice_Assistant_Set_Vad_Param(2221),
    SAMICorePropertyId_Voice_Assistant_Send_BidirectionalTTS(2222),
    SAMICorePropertyId_Voice_Assistant_Send_BidirectionalTTSEnd(2223),
    SAMICorePropertyId_Voice_Assistant_BidirectionalTTS_EndTTS(2224),
    SAMICorePropertyId_Voice_Assistant_Create_Session(2226),
    SAMICorePropertyId_Voice_Assistant_Remove_Session(2227),
    SAMICorePropertyId_Voice_Assistant_Update_UI_Context(2229),
    SAMICorePropertyId_Voice_Assistant_Upload_Info(2230),
    SAMICorePropertyId_Voice_Assistant_Trace_Span_Param(2231),
    SAMICorePropertyId_Voice_Assistant_Set_VAD_Info(2232),
    SAMICorePropertyId_Voice_Assistant_Set_Player_Status(2233),
    SAMICorePropertyId_Voice_Assistant_Request_Chat(2234),
    SAMICorePropertyId_Voice_Assistant_Mute_Call(2235),
    SAMICorePropertyId_Voice_Assistant_Unmute_Call(2236),
    SAMICorePropertyId_Voice_Assistant_Set_Loudness_Strategy_Param(2237),
    SAMICorePropertyId_PostProcess_Loudness_Strategy_Param(2237),
    SAMICorePropertyId_Voice_Assistant_Update_Audio_Config(2238),
    SAMICorePropertyId_Voice_Assistant_Set_Wakeup_Init_Info(2240),
    SAMICorePropertyId_Voice_Assistant_Get_Wakeup_Audio(2241),
    SAMICorePropertyId_Voice_Assistant_InitVad(2250),
    SAMICorePropertyId_Voice_Assistant_Vad_Reset(2251),
    SAMICorePropertyId_Voice_Assistant_UploadInfo(2252),
    SAMICorePropertyId_Voice_Assistant_UploadMem(2253),
    SAMICorePropertyId_Voice_Assistant_Set_Chat_Param(2256),
    SAMICorePropertyId_Voice_Assistant_Update_Asr_Extra(2257),
    SAMICorePropertyId_Voice_Assistant_Set_Multimodal_Status(2258),
    SAMICorePropertyId_Voice_Assistant_V2(2300),
    SAMICorePropertyId_LP_KWS_Result(2400),
    SAMICorePropertyId_First_Wakeup_Info(2401),
    SAMICorePropertyId_2nd_Wakeup_Model_Path(2402),
    SAMICorePropertyId_LP_KWS_Audio_config(2403),
    SAMICorePropertyId_LP_KWS_App_Status(2404),
    SAMICorePropertyId_LP_KWS_Query_Type(2405),
    SAMICorePropertyId_2nd_Wakeup_Threshold(2407),
    SAMICorePropertyId_LP_KWS_Sid_Process_Async(2408),
    SAMICorePropertyId_LP_KWS_Sid_TID(2409),
    SAMICorePropertyId_Enable_LP_KWS_Sid_Verify(2410),
    SAMICorePropertyId_AIS_Data(2500),
    SAMICorePropertyId_AIS_Ability(2501),
    SAMICorePropertyId_AIS_AbilityReset(2502),
    SAMICorePropertyId_ASR_Online_Reset_Recognition_V2(2600),
    SAMICorePropertyId_ASR_Online_Force_Finish_V2(2601),
    SAMICorePropertyId_ASR_Online_Wait_Stop_V2(2602),
    SAMICorePropertyId_ASR_Online_Interrupt(2603),
    SAMICorePropertyId_Voice_Assistant_AudioPlayer_Start(2700),
    SAMICorePropertyId_Voice_Assistant_AudioPlayer_Pause(2701),
    SAMICorePropertyId_Voice_Assistant_AudioPlayer_Stop(2702),
    SAMICorePropertyId_Voice_Assistant_AudioPlayer_SetVolume(2703),
    SAMICorePropertyId_Voice_Assistant_Get_PlayerStatus(2704),
    SAMICorePropertyId_Voice_Assistant_Process_Server_Event(2800),
    SAMICorePropertyId_Offline_Full_Duplex(3000);

    public static final HashMap<Integer, SAMICorePropertyId> intToEnumMap = new HashMap<>();
    private int value;

    static {
        SAMICorePropertyId[] values = values();
        for (int i = 0; i < 211; i++) {
            SAMICorePropertyId sAMICorePropertyId = values[i];
            intToEnumMap.put(Integer.valueOf(sAMICorePropertyId.getValue()), sAMICorePropertyId);
        }
    }

    SAMICorePropertyId(int i) {
        this.value = 0;
        this.value = i;
    }

    public static SAMICorePropertyId fromInt(int i) {
        return intToEnumMap.get(Integer.valueOf(i));
    }

    public int getValue() {
        return this.value;
    }
}
